function createfigure(X1, YMatrix1, X2, Y1, X3, Y2)
%CREATEFIGURE(X1, YMATRIX1, X2, Y1, X3, Y2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 12-Jul-2018 12:07:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',30,'Marker','.','LineStyle','none');
set(plot1(2),'Color',[1 0 0]);

% Create plot
plot(X2,Y1,'MarkerSize',30,'Marker','.','LineStyle','none','Color',[1 0 0]);

% Create plot
plot(X3,Y2,'LineWidth',4,'Color',[1 0 0]);

% Create xlabel
xlabel('X and X2','FontSize',11);

% Create title
title('Function to approximate.','FontSize',11);

% Create ylabel
ylabel('T and Y2','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1 4]);
box(axes1,'on');
